apiVersion: v1
kind: PersistentVolume
metadata:
  name: kubevirt-pv-15gib
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/data"
