apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubevirt-pvc-15gib
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: standard 