apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: busybox-server
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: a.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: busybox-server-type-1
            port:
              number: 8080
  - host: b.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: busybox-server-type-1
            port:
              number: 8081
