apiVersion: v1
kind: PersistentVolume
metadata:
  name: control-panel-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
    type: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vm-development-1
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
