apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: control-panel-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      kubernetes.io/hostname: vm-development-1
